@SuperHeroAPI_HostAddress = https://localhost:7039

GET {{SuperHeroAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SuperHeroAPI_HostAddress}}/weatherforecast

###

POST {{SuperHeroAPI_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHero
}

###
